# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSRJ7LPcvj-LEmxxRVBey2w0CAMUZB5B
"""

from .agent import root_agent

__all__ = ["root_agent"]