{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOrnd28LB4M1cqS8ZAJppzW",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rajput-t/E-Com_Support_Agent_googleADK/blob/main/agent.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "PjZ5h-8uuVTB"
      },
      "outputs": [],
      "source": [
        "from typing import Dict\n",
        "\n",
        "from google.adk.agents import LlmAgent\n",
        "from google.adk.models.google_llm import Gemini\n",
        "from google.adk.tools import load_memory\n",
        "from google.genai import types\n",
        "\n",
        "# Retry config similar to course notebooks\n",
        "retry_config = types.HttpRetryOptions(\n",
        "    attempts=5,\n",
        "    exp_base=7,\n",
        "    initial_delay=1,\n",
        "    http_status_codes=[429, 500, 503, 504],\n",
        ")\n",
        "\n",
        "\n",
        "# ---------- TOOLS ----------\n",
        "\n",
        "def get_product_info(product_name: str) -> Dict[str, str]:\n",
        "    \"\"\"\n",
        "    Returns basic product information for a given product name.\n",
        "\n",
        "    In a real system this would call a database or external API.\n",
        "    Here we return mock data for demo & evaluation.\n",
        "    \"\"\"\n",
        "    product_catalog = {\n",
        "        \"macbook pro 14\": {\n",
        "            \"name\": 'MacBook Pro 14\"',\n",
        "            \"price\": \"$1,999\",\n",
        "            \"stock\": \"In Stock (22 units)\",\n",
        "            \"details\": \"M3 Pro chip, 18GB RAM, 512GB SSD\",\n",
        "        },\n",
        "        \"dell xps 15\": {\n",
        "            \"name\": \"Dell XPS 15\",\n",
        "            \"price\": \"$1,299\",\n",
        "            \"stock\": \"In Stock (45 units)\",\n",
        "            \"details\": '15.6\" display, 16GB RAM, 512GB SSD',\n",
        "        },\n",
        "        \"pixel 9\": {\n",
        "            \"name\": \"Pixel 9\",\n",
        "            \"price\": \"$899\",\n",
        "            \"stock\": \"Low stock (5 units)\",\n",
        "            \"details\": \"128GB storage, Obsidian Black\",\n",
        "        },\n",
        "    }\n",
        "\n",
        "    key = product_name.lower().strip()\n",
        "    if key in product_catalog:\n",
        "        return {\n",
        "            \"status\": \"success\",\n",
        "            \"product_name\": product_catalog[key][\"name\"],\n",
        "            \"price\": product_catalog[key][\"price\"],\n",
        "            \"stock\": product_catalog[key][\"stock\"],\n",
        "            \"details\": product_catalog[key][\"details\"],\n",
        "        }\n",
        "    else:\n",
        "        available = \", \".join(v[\"name\"] for v in product_catalog.values())\n",
        "        return {\n",
        "            \"status\": \"not_found\",\n",
        "            \"error\": f\"No product found for '{product_name}'. \"\n",
        "                     f\"Available examples: {available}\",\n",
        "        }\n",
        "\n",
        "\n",
        "def get_order_status(order_id: str) -> Dict[str, str]:\n",
        "    \"\"\"\n",
        "    Returns a mock order status for a given order ID.\n",
        "    \"\"\"\n",
        "    mock_orders = {\n",
        "        \"ORD123\": {\n",
        "            \"status\": \"Shipped\",\n",
        "            \"eta\": \"3-5 business days\",\n",
        "            \"carrier\": \"DHL\",\n",
        "        },\n",
        "        \"ORD456\": {\n",
        "            \"status\": \"Processing\",\n",
        "            \"eta\": \"Ships in 1-2 days\",\n",
        "            \"carrier\": \"N/A\",\n",
        "        },\n",
        "        \"ORD789\": {\n",
        "            \"status\": \"Delivered\",\n",
        "            \"eta\": \"Delivered yesterday\",\n",
        "            \"carrier\": \"FedEx\",\n",
        "        },\n",
        "    }\n",
        "\n",
        "    key = order_id.upper().strip()\n",
        "    if key in mock_orders:\n",
        "        return {\n",
        "            \"status\": \"success\",\n",
        "            \"order_id\": key,\n",
        "            \"order_status\": mock_orders[key][\"status\"],\n",
        "            \"eta\": mock_orders[key][\"eta\"],\n",
        "            \"carrier\": mock_orders[key][\"carrier\"],\n",
        "        }\n",
        "    else:\n",
        "        return {\n",
        "            \"status\": \"not_found\",\n",
        "            \"order_id\": key,\n",
        "            \"error\": f\"No order found with ID {key}. \"\n",
        "                     \"Please check the ID and try again.\",\n",
        "        }\n",
        "\n",
        "\n",
        "def get_return_policy(country: str) -> str:\n",
        "    \"\"\"\n",
        "    Returns a simple, country-dependent return policy description.\n",
        "    \"\"\"\n",
        "    country_lower = country.lower().strip()\n",
        "    if country_lower in {\"india\", \"in\"}:\n",
        "        return (\n",
        "            \"For India: You can return most items within 10 days of delivery. \"\n",
        "            \"Pickup is arranged for eligible locations. Refunds are issued to the original payment method.\"\n",
        "        )\n",
        "    if country_lower in {\"united states\", \"usa\", \"us\"}:\n",
        "        return (\n",
        "            \"For the US: Most items are returnable within 30 days. \"\n",
        "            \"You can drop off at our partner locations or ship back with a prepaid label.\"\n",
        "        )\n",
        "    if country_lower in {\"united kingdom\", \"uk\"}:\n",
        "        return (\n",
        "            \"For the UK: You have 14 days to initiate a return from the delivery date. \"\n",
        "            \"Refunds are processed within 5–7 business days after inspection.\"\n",
        "        )\n",
        "    return (\n",
        "        f\"For {country}: Our standard policy is a 15-day return window from delivery, \"\n",
        "        \"subject to local regulations. Some items (e.g., software, opened earphones) may be non-returnable.\"\n",
        "    )\n",
        "\n",
        "\n",
        "# ---------- ROOT AGENT ----------\n",
        "\n",
        "root_agent = LlmAgent(\n",
        "    model=Gemini(model=\"gemini-2.5-flash-lite\", retry_options=retry_config),\n",
        "    name=\"ecom_support_agent\",\n",
        "    description=\"Customer support agent for an electronics e-commerce store.\",\n",
        "    instruction=(\n",
        "        \"You are a helpful, concise customer support agent for an online electronics store.\\n\\n\"\n",
        "        \"Capabilities:\\n\"\n",
        "        \"- Explain product details, pricing, and availability using the get_product_info tool.\\n\"\n",
        "        \"- Check order status with the get_order_status tool.\\n\"\n",
        "        \"- Explain the return policy using the get_return_policy tool.\\n\"\n",
        "        \"- Use the load_memory tool when you need to recall user preferences from past sessions.\\n\\n\"\n",
        "        \"Rules:\\n\"\n",
        "        \"- Always call the appropriate tool instead of guessing.\\n\"\n",
        "        \"- If a tool reports 'not_found', apologize and offer alternatives.\\n\"\n",
        "        \"- Keep answers friendly and easy to understand.\\n\"\n",
        "        \"- When returning order status, mention status, ETA, and (if available) carrier.\"\n",
        "    ),\n",
        "    tools=[\n",
        "        get_product_info,\n",
        "        get_order_status,\n",
        "        get_return_policy,\n",
        "        load_memory,  # lets the agent search long-term memory (if a MemoryService is attached)\n",
        "    ],\n",
        ")"
      ]
    }
  ]
}