# -*- coding: utf-8 -*-
"""agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdLu_vLaIyV2lGLgXY91qfbIaNKJL4Z_
"""

from typing import Dict

from google.adk.agents import LlmAgent
from google.adk.models.google_llm import Gemini
from google.adk.tools import load_memory
from google.genai import types

# Retry config similar to course notebooks
retry_config = types.HttpRetryOptions(
    attempts=5,
    exp_base=7,
    initial_delay=1,
    http_status_codes=[429, 500, 503, 504],
)


# ---------- TOOLS ----------

def get_product_info(product_name: str) -> Dict[str, str]:
    """
    Returns basic product information for a given product name.

    In a real system this would call a database or external API.
    Here we return mock data for demo & evaluation.
    """
    product_catalog = {
        "macbook pro 14": {
            "name": 'MacBook Pro 14"',
            "price": "$1,999",
            "stock": "In Stock (22 units)",
            "details": "M3 Pro chip, 18GB RAM, 512GB SSD",
        },
        "dell xps 15": {
            "name": "Dell XPS 15",
            "price": "$1,299",
            "stock": "In Stock (45 units)",
            "details": '15.6" display, 16GB RAM, 512GB SSD',
        },
        "pixel 9": {
            "name": "Pixel 9",
            "price": "$899",
            "stock": "Low stock (5 units)",
            "details": "128GB storage, Obsidian Black",
        },
    }

    key = product_name.lower().strip()
    if key in product_catalog:
        return {
            "status": "success",
            "product_name": product_catalog[key]["name"],
            "price": product_catalog[key]["price"],
            "stock": product_catalog[key]["stock"],
            "details": product_catalog[key]["details"],
        }
    else:
        available = ", ".join(v["name"] for v in product_catalog.values())
        return {
            "status": "not_found",
            "error": f"No product found for '{product_name}'. "
                     f"Available examples: {available}",
        }


def get_order_status(order_id: str) -> Dict[str, str]:
    """
    Returns a mock order status for a given order ID.
    """
    mock_orders = {
        "ORD123": {
            "status": "Shipped",
            "eta": "3-5 business days",
            "carrier": "DHL",
        },
        "ORD456": {
            "status": "Processing",
            "eta": "Ships in 1-2 days",
            "carrier": "N/A",
        },
        "ORD789": {
            "status": "Delivered",
            "eta": "Delivered yesterday",
            "carrier": "FedEx",
        },
    }

    key = order_id.upper().strip()
    if key in mock_orders:
        return {
            "status": "success",
            "order_id": key,
            "order_status": mock_orders[key]["status"],
            "eta": mock_orders[key]["eta"],
            "carrier": mock_orders[key]["carrier"],
        }
    else:
        return {
            "status": "not_found",
            "order_id": key,
            "error": f"No order found with ID {key}. "
                     "Please check the ID and try again.",
        }


def get_return_policy(country: str) -> str:
    """
    Returns a simple, country-dependent return policy description.
    """
    country_lower = country.lower().strip()
    if country_lower in {"india", "in"}:
        return (
            "For India: You can return most items within 10 days of delivery. "
            "Pickup is arranged for eligible locations. Refunds are issued to the original payment method."
        )
    if country_lower in {"united states", "usa", "us"}:
        return (
            "For the US: Most items are returnable within 30 days. "
            "You can drop off at our partner locations or ship back with a prepaid label."
        )
    if country_lower in {"united kingdom", "uk"}:
        return (
            "For the UK: You have 14 days to initiate a return from the delivery date. "
            "Refunds are processed within 5–7 business days after inspection."
        )
    return (
        f"For {country}: Our standard policy is a 15-day return window from delivery, "
        "subject to local regulations. Some items (e.g., software, opened earphones) may be non-returnable."
    )


# ---------- ROOT AGENT ----------

root_agent = LlmAgent(
    model=Gemini(model="gemini-2.5-flash-lite", retry_options=retry_config),
    name="ecom_support_agent",
    description="Customer support agent for an electronics e-commerce store.",
    instruction=(
        "You are a helpful, concise customer support agent for an online electronics store.\n\n"
        "Capabilities:\n"
        "- Explain product details, pricing, and availability using the get_product_info tool.\n"
        "- Check order status with the get_order_status tool.\n"
        "- Explain the return policy using the get_return_policy tool.\n"
        "- Use the load_memory tool when you need to recall user preferences from past sessions.\n\n"
        "Rules:\n"
        "- Always call the appropriate tool instead of guessing.\n"
        "- If a tool reports 'not_found', apologize and offer alternatives.\n"
        "- Keep answers friendly and easy to understand.\n"
        "- When returning order status, mention status, ETA, and (if available) carrier."
    ),
    tools=[
        get_product_info,
        get_order_status,
        get_return_policy,
        load_memory,  # lets the agent search long-term memory (if a MemoryService is attached)
    ],
)