# -*- coding: utf-8 -*-
"""run_local

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIWgjeJF65bpvvBtZ5APBR8xUJ2Nl0UF
"""

import asyncio
import os

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.memory import InMemoryMemoryService
from google.adk.plugins.logging_plugin import LoggingPlugin
from google.genai import types

from ecom_support_agent import root_agent


APP_NAME = "EcomSupportApp"
USER_ID = "demo_user"


async def main():
    # Make sure GOOGLE_API_KEY is set in your environment
    if "GOOGLE_API_KEY" not in os.environ:
        raise RuntimeError(
            "Please set the GOOGLE_API_KEY environment variable before running."
        )

    session_service = InMemorySessionService()
    memory_service = InMemoryMemoryService()

    runner = Runner(
        agent=root_agent,
        app_name=APP_NAME,
        session_service=session_service,
        memory_service=memory_service,
        plugins=[LoggingPlugin()],  # observability
    )

    session_id = "local_demo_session"

    print("E-Com Support Agent. Type 'exit' to quit.\n")

    while True:
        user_text = input("You > ").strip()
        if not user_text:
            continue
        if user_text.lower() in {"exit", "quit"}:
            print("Bye! 👋")
            break

        content = types.Content(parts=[types.Part(text=user_text)])

        async for event in runner.run_async(
            user_id=USER_ID, session_id=session_id, new_message=content
        ):
            if event.is_final_response() and event.content and event.content.parts:
                # Print the first text part
                for part in event.content.parts:
                    if getattr(part, "text", None):
                        print("Agent >", part.text)
                        break


if __name__ == "__main__":
    asyncio.run(main())